feat(e2e): init e2e and ex auth-test
2110336-2565-2/Sec33-group1-MeowMeow pull request #81
Opened 2023-03-23 11:00 UTC by TendonT52

## Change made

- [ ] Bug fixes
- [x] New features
- [ ] Breaking changes

## Describe what you have done

-

### New Features

- Add end to end test

### Fix

-

### Others

-

2023-03-23 23:51 UTC, PongDev requested changes
a little change request, other is LGTM!

2023-03-23 23:51 UTC, PongDev commented on apps/backend/src/prisma/prisma.service.ts
> +  }
personally, I think use separate database may be more practical. This code is seem very destructive if miss use.

2023-03-23 23:51 UTC, PongDev commented on apps/backend/src/prisma/prisma.service.ts
> +  }
I think we may start test db from docker compose and run it with inject env to prisma or sth like that.

2023-03-23 23:51 UTC, PongDev commented on apps/backend/test/jest-e2e.json
> +  "rootDir": "../",
I am not sure if this will break other unit test.

2023-03-23 23:51 UTC, PongDev commented on package.json
> +    "build:backend": "turbo run build --filter config --filter database --filter types",
oh, this is good idea, we may also change dev:backend to run build:backend before run dev in the future to reduce duplicated code.

2023-03-23 23:51 UTC, PongDev commented on apps/backend/src/prisma/prisma.service.ts
> +  }
also to cleanup, may delete the db with remove of docker volume

2023-03-24 00:50 UTC, TendonT52 commented
I will use another way to do test 
close this for now 
will major change in e2e soon

2023-03-24 00:50 UTC, closed without merging